sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

node_js:
  - '8'
cache:
  directories:
    - node_modules
before_install:
  - npm install -g node-gyp
env:
  global:
  - CXX=g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - libgnome-keyring-dev
      - xz-utils
      - xorriso
      - xvfb
      - libsecret-1-dev
      - libgconf-2-4 
      - libcanberra-gtk-module 
      - libappindicator1
      - fakeroot

install:
  - npm install -g npm@latest
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - npm run make

before_deploy:
  - ls /out/make
